version: '3'
services:
  db:
    image: mariadb
    command: bundle exec unicorn_rails -c config/unicorn.rb -E production -D
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  web:
    build: .
      #context: ./nginx_docker_production
    #　↑ 本番環境用に作ったディレクトリでnginxによるコンテナを構築する。
    command: bundle exec unicorn_rails -c config/unicorn.rb -E production -D
    volumes:
       - .:/workdir
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db


    